spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarefas
    username: postgresql
    password: postgresql
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


